unpin konnectivity-client and cluster-api for 1.26_rebase
this is essentially just a version bump on
  sigs.k8s.io/apiserver-network-proxy/konnectivity-client and
  sigs.k8s.io/cluster-api which were pinned previously.

needed to fix the below build errors:

    go build -mod=vendor -trimpath -ldflags "-X github.com/openshift/cluster-network-operator/pkg/version.versionFromGit="v0.0.0-unknown-6f95b1927" -X github.com/openshift/cluster-network-operator/pkg/version.commitFromGit="6f95b1927" -X github.com/openshift/cluster-network-operator/pkg/version.gitTreeState="clean" -X github.com/openshift/cluster-network-operator/pkg/version.buildDate="2023-02-09T19:40:53Z" " github.com/openshift/cluster-network-operator/cmd/cluster-network-check-endpoints
    # k8s.io/apiserver/pkg/server/egressselector
    vendor/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go:48:9: undefined: client.Metrics
    make: *** [vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk:16: build] Error 2

-AND-

    # sigs.k8s.io/controller-runtime/pkg/cache
    vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go:144:9: cannot use i.Informer (variable of type "k8s.io/client-go/tools/cache".SharedIndexInformer) as type Informer in return statement:
            "k8s.io/client-go/tools/cache".SharedIndexInformer does not implement Informer (wrong type for AddEventHandler method)
                    have AddEventHandler(handler "k8s.io/client-go/tools/cache".ResourceEventHandler) ("k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration, error)
                    want AddEventHandler(handler "k8s.io/client-go/tools/cache".ResourceEventHandler)
    vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go:158:9: cannot use i.Informer (variable of type "k8s.io/client-go/tools/cache".SharedIndexInformer) as type Informer in return statement:
            "k8s.io/client-go/tools/cache".SharedIndexInformer does not implement Informer (wrong type for AddEventHandler method)
                    have AddEventHandler(handler "k8s.io/client-go/tools/cache".ResourceEventHandler) ("k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration, error)
                    want AddEventHandler(handler "k8s.io/client-go/tools/cache".ResourceEventHandler)

Then:
- go get -u sigs.k8s.io/controller-runtime
- go get -t github.com/openshift/cluster-network-operator/pkg/apply
- go get -t github.com/openshift/cluster-network-operator/pkg/network
- go mod tidy; go mod vendor

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>