Bump to k8s v1.32
 ❯ rg 'k8s.io|openshift' go.mod | rg -v 'indirect|module' | awk '{print "go get -u",$1}'
    go get -u github.com/openshift/build-machinery-go
    go get -u k8s.io/api
    go get -u k8s.io/apimachinery
    go get -u k8s.io/code-generator
    go get -u k8s.io/component-base
    go get -u k8s.io/klog/v2
    go get -u k8s.io/kube-proxy
    go get -u k8s.io/utils
    go get -u sigs.k8s.io/controller-runtime
    go get -u github.com/openshift/api
    go get -u github.com/openshift/client-go
    go get -u github.com/openshift/library-go
    go get -u github.com/openshift/machine-config-operator
    go get -u k8s.io/apiextensions-apiserver
    go get -u k8s.io/client-go
    go get -u sigs.k8s.io/controller-tools

    rg 'k8s.io|openshift' go.mod | rg -v 'indirect|module' | awk '{print "go get -u",$1}'

    ❯ go mod tidy
    ❯ go mod vendor

    ❯ go get github.com/openshift/machine-config-operator@24d9a767570d294d46a47a37fff9fb99b2304d4b

    ❯ go mod tidy; go mod vendor
    For the error below run go mod tidy
    go: finding module for package github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1
    go: downloading github.com/openshift/machine-config-operator v3.11.0+incompatible
    go: github.com/openshift/cluster-network-operator/pkg/bootstrap imports
            github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1: create zip: pkg/controller/template/test_data/templates/aws/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/aws/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
    pkg/controller/template/test_data/templates/aws/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/aws/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
    pkg/controller/template/test_data/templates/libvirt/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/libvirt/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
    pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
    go: github.com/openshift/cluster-network-operator/pkg/bootstrap imports
            github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1: no required module provides package github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1; to add it:
            go get github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1
    go: github.com/openshift/cluster-network-operator/pkg/controller/operconfig imports
            github.com/openshift/machine-config-operator/pkg/controller/common imports
            github.com/coreos/ignition/v2/config/v3_4/types imports
            github.com/aws/aws-sdk-go/aws/arn: missing go.sum entry for module providing package github.com/aws/aws-sdk-go/aws/arn (imported by github.com/coreos/ignition/v2/config/v3_4/types); to add:
            go get github.com/coreos/ignition/v2/config/v3_4/types@v2.15.0
    ❯ go mod tidy

    ❯ go mod tidy
    go: finding module for package github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1
    go: downloading github.com/openshift/machine-config-operator v3.11.0+incompatible
    go: github.com/openshift/cluster-network-operator/pkg/bootstrap imports
            github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1: create zip: pkg/controller/template/test_data/templates/aws/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/aws/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
    pkg/controller/template/test_data/templates/aws/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/aws/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
    pkg/controller/template/test_data/templates/libvirt/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/libvirt/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
    pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'

      "github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1"
      "github.com/openshift/api/machineconfiguration/v1"

    ❯ go mod tidy; go mod vendor

    pkg/controller/statusmanager/machineconfig_status.go:234:13: undefined: mcfgv1.IsMachineConfigPoolConditionTrue
    pkg/controller/statusmanager/machineconfig_status.go:245:13: undefined: mcfgv1.IsMachineConfigPoolConditionTrue
    make: *** [vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk:16: build] Error 1

    ❯ go mod tidy; go mod vendor

    ❯ make test
    go test -mod=vendor -race ./pkg/... ./cmd/...
    ?       github.com/openshift/cluster-network-operator/pkg/apis/network/v1       [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/bootstrap     [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/client        [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/client/fake   [no test files]
    ok      github.com/openshift/cluster-network-operator/pkg/apply 1.320s
    ?       github.com/openshift/cluster-network-operator/pkg/cmd/checkendpoints    [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/cmd/checkendpoints/trace      [no test files]
    ok      github.com/openshift/cluster-network-operator/pkg/cmd/checkendpoints/controller 1.366s
    ok      github.com/openshift/cluster-network-operator/pkg/cmd/checkendpoints/operatorcontrolplane/podnetworkconnectivitycheck/v1alpha1helpers   1.029s
    ?       github.com/openshift/cluster-network-operator/pkg/controller    [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/controller/allowlist  [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/controller/configmap_ca_injector      [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/controller/connectivitycheck  [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/controller/dashboards [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/controller/egress_router      [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/controller/eventrecorder      [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/controller/ingressconfig      [no test files]
    ok      github.com/openshift/cluster-network-operator/pkg/controller/clusterconfig      1.482s
    ok      github.com/openshift/cluster-network-operator/pkg/controller/infrastructureconfig       1.179s
    ?       github.com/openshift/cluster-network-operator/pkg/controller/pki        [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/controller/proxyconfig        [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/controller/signer     [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/names [no test files]
    ok      github.com/openshift/cluster-network-operator/pkg/controller/operconfig 1.695s
    ?       github.com/openshift/cluster-network-operator/pkg/operator      [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/platform      [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/util  [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/util/ipsec    [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/util/machineconfig    [no test files]
    ?       github.com/openshift/cluster-network-operator/pkg/version       [no test files]
    ?       github.com/openshift/cluster-network-operator/cmd/cluster-network-check-endpoints       [no test files]
    ?       github.com/openshift/cluster-network-operator/cmd/cluster-network-check-target  [no test files]
    ?       github.com/openshift/cluster-network-operator/cmd/cluster-network-operator      [no test files]
    ok      github.com/openshift/cluster-network-operator/pkg/controller/statusmanager      3.136s
    ok      github.com/openshift/cluster-network-operator/pkg/hypershift    1.034s
    ok      github.com/openshift/cluster-network-operator/pkg/network       16.302s
    ok      github.com/openshift/cluster-network-operator/pkg/render        1.039s
    ok      github.com/openshift/cluster-network-operator/pkg/util/ip       1.018s
    ok      github.com/openshift/cluster-network-operator/pkg/util/k8s      1.071s
    ok      github.com/openshift/cluster-network-operator/pkg/util/proxyconfig      1.020s
    ok      github.com/openshift/cluster-network-operator/pkg/util/validation       1.022s

    migrate ApplyOperatorStatus to use SSA
    seems this is now done in library-go in 4.19 so need to follow suite
    here in CNO. Here for managementstatecontroller [0] caused an e2e
    test case to fail which is how it was noticed.

    [0] https://github.com/openshift/library-go/commit/d318142bce78adebec0c2fc31472152842b14f5d

    Add the comparison in the functions ApplyOperatorSpec and  ApplyOperatorStatus that was removed as per [1]
    [1] https://github.com/openshift/cluster-network-operator/compare/2c0dc51321134c8fd2912386d1f2634b25b2047a..13233dc023f1e05901bb5774502fea4c15af99a5