apply: Add missing error check in MergeObjectForUpdate
Fixes:
pkg/apply/merge.go:44:24: Error return value of `MergeMetadataForUpdate` is not checked (errcheck)
        MergeMetadataForUpdate(current, updated)

Signed-off-by: Dave Tucker <dave@dtucker.co.uk>