apply: Fix unused error value
Fixes:

pkg/apply/merge.go:109:22: Error return value of `uns.SetNestedField` is not checked (errcheck)
			uns.SetNestedField(updated.Object, curSecrets, "secrets")

Signed-off-by: Dave Tucker <dave@dtucker.co.uk>