Update openshift/api
Did go get github.com/openshift/api@596420900030c87b81be311e02b4b8726ff5d56c
to get https://github.com/openshift/api/pull/2629
followed by go mod vendor and go mod tidy

Then when I ran make it failed with:

surya@fedora:~/go/src/github.com/openshift/cluster-network-operator$ make
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
go build -mod=vendor -trimpath -ldflags "-X github.com/openshift/cluster-network-operator/pkg/version.versionFromGit="v0.0.0-unknown-00ab125d3" -X github.com/openshift/cluster-network-operator/pkg/version.commitFromGit="00ab125d3" -X github.com/openshift/cluster-network-operator/pkg/version.gitTreeState="dirty" -X github.com/openshift/cluster-network-operator/pkg/version.buildDate="2026-01-15T13:06:12Z" " github.com/openshift/cluster-network-operator/cmd/cluster-network-check-endpoints
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gathererconfig.go:13:18: undefined: configv1.GathererState
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gathererconfig.go:33:69: undefined: configv1.GathererState
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gatherconfig.go:12:24: undefined: configv1.DataPolicyOption
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gatherconfig.go:26:76: undefined: configv1.DataPolicyOption
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gatherers.go:12:19: undefined: configv1.GatheringMode
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gatherers.go:25:63: undefined: configv1.GatheringMode
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/storage.go:12:29: undefined: configv1.StorageType
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gcpserviceendpoint.go:12:17: undefined: configv1.GCPServiceEndpointName
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gcpserviceendpoint.go:25:72: undefined: configv1.GCPServiceEndpointName
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/insightsdatagather.go:43:61: undefined: configv1.InsightsDataGather
vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/insightsdatagather.go:43:61: too many errors
make: *** [vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk:16: build] Error 1

Hence had to do:

go get -u github.com/openshift/client-go

go mod tidy
go mod vendor

Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>