k8s rebase
❯ rg 'k8s.io|openshift' go.mod | rg -v 'indirect|module' | awk '{print "go get -u",$1}'
go get -u github.com/openshift/build-machinery-go
go get -u k8s.io/api
go get -u k8s.io/apimachinery
go get -u k8s.io/code-generator
go get -u k8s.io/component-base
go get -u k8s.io/klog/v2
go get -u k8s.io/kube-proxy
go get -u k8s.io/utils
go get -u sigs.k8s.io/controller-runtime
go get -u github.com/openshift/api
go get -u github.com/openshift/client-go
go get -u github.com/openshift/library-go
go get -u github.com/openshift/machine-config-operator
go get -u k8s.io/apiextensions-apiserver
go get -u k8s.io/client-go
go get -u sigs.k8s.io/controller-tools

rg 'k8s.io|openshift' go.mod | rg -v 'indirect|module' | awk '{print "go get -u",$1}' | sh
--- <SNIPPING OUTUT FOR BREVITY>

❯ go mod tidy
❯ go mod vendor

--- next make build fails with this:
--- k8s.io/apiserver/pkg/cel/environment
 vendor/k8s.io/apiserver/pkg/cel/environment/base.go:176:19: cannot use ext.TwoVarComprehensions (value of type func(options ...ext.TwoVarComprehensionsOption) "github.com/google/cel-go/cel".EnvOption) as func() "github.com/google/cel-go/cel".EnvOption value in argument to UnversionedLib
 make: *** [vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk:16: build] Error 1

--- this fix was found to downgrade cel-go to 0.22.0

❯ go mod edit -replace=github.com/google/cel-go=github.com/google/cel-go@v0.22.0

❯ go mod tidy; go mod vendor

--- make build fails multiple times in this process because some calls are now expecting a
--- PassiveClock argument, and those are fixed by adding clock.RealClock{} in the right
--- places each time

--- MCO also faced this PassiveClock issue and we need to bring in their changes after
--- their already merged kube rebase:

❯ go get github.com/openshift/machine-config-operator@24d9a767570d294d46a47a37fff9fb99b2304d4b
--- <SNIPPING OUTUT FOR BREVITY>

❯ go mod tidy; go mod vendor

--- the previous version of MCO was 2+ years old and one of their APIs was moved to the
--- openshift/api project resulting in the following tidy error:

❯ go mod tidy
go: finding module for package github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1
go: downloading github.com/openshift/machine-config-operator v3.11.0+incompatible
go: github.com/openshift/cluster-network-operator/pkg/bootstrap imports
        github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1: create zip: pkg/controller/template/test_data/templates/aws/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/aws/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
pkg/controller/template/test_data/templates/aws/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/aws/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/libvirt/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt: malformed file path "pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'

--- the fix is to replace all imports from this:
  "github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1"
--- to this:
  "github.com/openshift/api/machineconfiguration/v1"

--- there are 12 occurances and find/replace with IDE

❯ go mod tidy; go mod vendor

--- the next build error:

--- github.com/openshift/cluster-network-operator/pkg/controller/statusmanager
pkg/controller/statusmanager/machineconfig_status.go:234:13: undefined: mcfgv1.IsMachineConfigPoolConditionTrue
pkg/controller/statusmanager/machineconfig_status.go:245:13: undefined: mcfgv1.IsMachineConfigPoolConditionTrue
make: *** [vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk:16: build] Error 1

--- IsMachineConfigPoolConditionTrue did not make it to the openshift/api and still exists
--- in the MCO project so those two cases need a new alias and still use the MCO api import
--- To fix in pkg/controller/statusmanager/machineconfig_status.go change the two calls
--- of "mcfgv1.IsMachineConfigPoolConditionTrue" to "mcomcfgv1.IsMachineConfigPoolConditionTrue"
--- and add this to imports:
--- mcomcfgv1 "github.com/openshift/machine-config-operator/pkg/apihelpers"

--- there are two more of this to fix that didn't come in this first build error. found
--- and fixed those.

❯ go mod tidy; go mod vendor

--- At this point the build passes, but "make verify" fails because "make update-gofmt" fails
--- so run "make update-gofmt" to apply those fixes and now "make verify" fails for a few
--- PassiveClock arguments. "make verify" will still fail at this point because the codegen
--- script sees the "git diff" as a failure, so commit the changes and "make verify" passes

--- and "make test" passes:

❯ make test
go test -mod=vendor -race ./pkg/... ./cmd/...
?       github.com/openshift/cluster-network-operator/pkg/apis/network/v1       [no test files]
?       github.com/openshift/cluster-network-operator/pkg/bootstrap     [no test files]
?       github.com/openshift/cluster-network-operator/pkg/client        [no test files]
?       github.com/openshift/cluster-network-operator/pkg/client/fake   [no test files]
ok      github.com/openshift/cluster-network-operator/pkg/apply 1.320s
?       github.com/openshift/cluster-network-operator/pkg/cmd/checkendpoints    [no test files]
?       github.com/openshift/cluster-network-operator/pkg/cmd/checkendpoints/trace      [no test files]
ok      github.com/openshift/cluster-network-operator/pkg/cmd/checkendpoints/controller 1.366s
ok      github.com/openshift/cluster-network-operator/pkg/cmd/checkendpoints/operatorcontrolplane/podnetworkconnectivitycheck/v1alpha1helpers   1.029s
?       github.com/openshift/cluster-network-operator/pkg/controller    [no test files]
?       github.com/openshift/cluster-network-operator/pkg/controller/allowlist  [no test files]
?       github.com/openshift/cluster-network-operator/pkg/controller/configmap_ca_injector      [no test files]
?       github.com/openshift/cluster-network-operator/pkg/controller/connectivitycheck  [no test files]
?       github.com/openshift/cluster-network-operator/pkg/controller/dashboards [no test files]
?       github.com/openshift/cluster-network-operator/pkg/controller/egress_router      [no test files]
?       github.com/openshift/cluster-network-operator/pkg/controller/eventrecorder      [no test files]
?       github.com/openshift/cluster-network-operator/pkg/controller/ingressconfig      [no test files]
ok      github.com/openshift/cluster-network-operator/pkg/controller/clusterconfig      1.482s
ok      github.com/openshift/cluster-network-operator/pkg/controller/infrastructureconfig       1.179s
?       github.com/openshift/cluster-network-operator/pkg/controller/pki        [no test files]
?       github.com/openshift/cluster-network-operator/pkg/controller/proxyconfig        [no test files]
?       github.com/openshift/cluster-network-operator/pkg/controller/signer     [no test files]
?       github.com/openshift/cluster-network-operator/pkg/names [no test files]
ok      github.com/openshift/cluster-network-operator/pkg/controller/operconfig 1.695s
?       github.com/openshift/cluster-network-operator/pkg/operator      [no test files]
?       github.com/openshift/cluster-network-operator/pkg/platform      [no test files]
?       github.com/openshift/cluster-network-operator/pkg/util  [no test files]
?       github.com/openshift/cluster-network-operator/pkg/util/ipsec    [no test files]
?       github.com/openshift/cluster-network-operator/pkg/util/machineconfig    [no test files]
?       github.com/openshift/cluster-network-operator/pkg/version       [no test files]
?       github.com/openshift/cluster-network-operator/cmd/cluster-network-check-endpoints       [no test files]
?       github.com/openshift/cluster-network-operator/cmd/cluster-network-check-target  [no test files]
?       github.com/openshift/cluster-network-operator/cmd/cluster-network-operator      [no test files]
ok      github.com/openshift/cluster-network-operator/pkg/controller/statusmanager      3.136s
ok      github.com/openshift/cluster-network-operator/pkg/hypershift    1.034s
ok      github.com/openshift/cluster-network-operator/pkg/network       16.302s
ok      github.com/openshift/cluster-network-operator/pkg/render        1.039s
ok      github.com/openshift/cluster-network-operator/pkg/util/ip       1.018s
ok      github.com/openshift/cluster-network-operator/pkg/util/k8s      1.071s
ok      github.com/openshift/cluster-network-operator/pkg/util/proxyconfig      1.020s
ok      github.com/openshift/cluster-network-operator/pkg/util/validation       1.022s

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>